version: 2
jobs:
  "hosted-unittests":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Check environment
          command: |
            env
            locale -a
            python --version  || true
            python2 --version || true
            python3 --version || true
            which scons
            scons --version
            which avr-g++
            avr-g++ --version
            which arm-none-eabi-g++
            arm-none-eabi-g++ --version

      - run:
          name: Unittest hosted
          command: |
            scons unittest

  "stm32-unittests":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Unittest STM32
          command: |
            scons unittest target=stm32

  "atmega-unittests":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Unittest AVR ATmega
          command: |
            scons unittest target=atmega

  "stm32f0-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F0 Series
          command: |
            scons check=examples examples=stm32f0_discovery,stm32f072_discovery,nucleo_f031k6

  "stm32f1-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F1 Series
          command: |
            scons check=examples examples=stm32f1_discovery,nucleo_f103rb,olimexino_stm32

  "stm32f3-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F3 Series
          command: |
            scons check=examples examples=stm32f3_discovery,nucleo_f303k8

  "stm32f4_discovery-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F4 Discovery Board
          command: |
            scons check=examples examples=stm32f4_discovery

  "stm32f4-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F4 Series (except STM32F4 Discovery Board)
          command: |
            scons check=examples examples=stm32f429_discovery,stm32f469_discovery,nucleo_f401re,nucleo_f411re,nucleo_f429zi

  "stm32f7-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32F7 Series
          command: |
            scons check=examples examples=stm32f746g_discovery

  "stm32l4-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples STM32L4 Series
          command: |
            scons check=examples examples=stm32l476_discovery,nucleo_l476rg

  "avr-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples ATmega Series
          command: |
            scons check=examples examples=avr,arduino_uno

  "lpcxpresso-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples LPCxpresso Board
          command: |
            scons check=examples examples=lpcxpresso


  "generic-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples from the generic folder (Mostly STM32 examples)
          command: |
            scons check=examples examples=generic

  "linux-examples":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Examples Linux
          command: |
            scons check=examples examples=linux,zmq

  "devices":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Check devices
          command: |
            scons check=devices

  "scripts-python2.7":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Check if tool scripts run with Python2
          command: |
            python2 tools/authors.py --handles --count --shoutout --since 2017-01-01
            python2 tools/system_design/builder/system_layout.py examples/communication/xml/communication.xml -o /tmp

  "scripts-python3":
    docker:
      - image: roboterclubaachen/modm-build:latest
    environment:
      - LANG: "en_US.UTF-8"
      - SCONS_LIB_DIR: "/usr/local/lib/python2.7/dist-packages/scons-2.5.1"
      - SCONSFLAGS: "-j3"
    steps:
      - checkout
      - run:
          name: Check if tool scripts run with Python3
          command: |
            python3 tools/authors.py --handles --count --shoutout --since 2017-01-01
            python3 tools/system_design/builder/system_layout.py examples/communication/xml/communication.xml -o /tmp

workflows:
  version: 2
  build:
    jobs:
      # Start longest running jobs first
      - "stm32f4_discovery-examples"
      - "stm32f4-examples"
      - "devices"
      - "hosted-unittests"
      - "stm32-unittests"
      - "atmega-unittests"
      - "stm32f0-examples"
      - "stm32f1-examples"
      - "stm32f3-examples"
      - "stm32f7-examples"
      - "stm32l4-examples"
      - "lpcxpresso-examples"
      - "generic-examples"
      - "linux-examples"
      - "avr-examples"
      - "scripts-python2.7"
      - "scripts-python3"
